version: '3.8'

services:
  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: hiv-rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ service
      - "15672:15672"  # Management interface
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - hivmedical-network

  # Auth Service Database
  auth-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hiv-auth-db
    environment:
      SA_PASSWORD: "NewStrongPassword123@"
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
    volumes:
      - auth_db_data:/var/opt/mssql
    networks:
      - hivmedical-network
    restart: unless-stopped

  # Patient Service Database
  patient-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hiv-patient-db
    environment:
      SA_PASSWORD: "NewStrongPassword123@"
      ACCEPT_EULA: "Y"
    ports:
      - "1436:1433"
    volumes:
      - patient_db_data:/var/opt/mssql
    networks:
      - hivmedical-network
    restart: unless-stopped

  # Authentication Service
  hivmedical-authentication-service:
    build:
      context: .
      dockerfile: HivMedical.AuthenticationSolution/Dockerfile
    container_name: hivmedical-authentication-service
    ports:
      - "5051:5051"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5051
      - ASPNETCORE_HTTPS_PORT=""
      - ConnectionStrings__DefaultConnection=Server=auth-db;Database=HivMedicalDB;User Id=sa;Password=NewStrongPassword123@;TrustServerCertificate=true;
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__Port=5672
    depends_on:
      - auth-db
      - rabbitmq
    networks:
      - hivmedical-network
    restart: unless-stopped

  # Patient Service
  patient-service:
    build:
      context: .
      dockerfile: HivMedical.PatientService/Dockerfile
    container_name: patient-service
    ports:
      - "5072:5072"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5072
      - ConnectionStrings__DefaultConnection=Server=patient-db;Database=HIVMedical_PatientDB;User Id=sa;Password=NewStrongPassword123@;TrustServerCertificate=true;
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__Port=5672
    depends_on:
      - patient-db
      - rabbitmq
    networks:
      - hivmedical-network
    restart: unless-stopped

  # API Gateway
  hivmedical-api-gateway:
    build:
      context: .
      dockerfile: HivMedical.Gateway/ApiGateway/Dockerfile
    container_name: hivmedical-api-gateway
    ports:
      - "5190:5190"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5190
      - ASPNETCORE_HTTPS_PORT=""
    depends_on:
      - hivmedical-authentication-service
      - patient-service
    networks:
      - hivmedical-network
    restart: unless-stopped

volumes:
  rabbitmq_data:
  auth_db_data:
  patient_db_data:

networks:
  hivmedical-network:
    driver: bridge
