version: '3.8'

services:
  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: hiv-rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ service
      - "15672:15672"  # Management interface
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - hivmedical-network

volumes:
  rabbitmq_data:

networks:
  hivmedical-network:
    driver: bridge